Repository thewumper/Wumpus, pull requests merged in 2024-02, with the labels that each got.

#23 Actually add the Testing project to the solution
  Core/WumpusCore/WumpusCore.sln
  Core/WumpusTesting/WumpusTesting.csproj
Labels: bug

#25 Move the solution up a folder
  Core/WumpusCore.sln
Labels: bug

#27 Add GitHub actions to run unit tests
  .github/workflows/run-tests.yml
  Core/WumpusTesting/WumpusTesting.csproj
Labels: enhancement

#29 Lots of documentation changes, new util methods, and changes to existing util methods. Also changed uint -> ushort.
  Core/WumpusCore/Controller/Controller.cs
  Core/WumpusCore/GameLocations/GameLocations.cs
Labels: documentation, enhancement

#30 uint -> ushort
  Core/WumpusCore/Player/Player.cs
Labels: enhancement

#32 new Player functionality
  Core/WumpusCore/Player/Player.cs
Labels: documentation, enhancement

#35 Update Unity and remove unneeded DLLs
  Unity/.gitignore
  Unity/Assets/DLL/WumpusCore.dll
  Unity/ProjectSettings/ProjectVersion.txt
Labels: enhancement

#36 Correctly reference the MSTest files in WumpusTesting
  Core/WumpusTesting/WumpusTesting.csproj
Labels: bug

#34 Add Trivia minigame
  .gitignore
  Core/WumpusCore/Minigame.cs
  Core/WumpusCore/Trivia/AnsweredQuestion.cs
  Core/WumpusCore/Trivia/AskableQuestion.cs
  Core/WumpusCore/Trivia/GameResult.cs
  Core/WumpusCore/Trivia/Question.cs
  Core/WumpusCore/Trivia/Questions.cs
  Core/WumpusCore/Trivia/Questions.json
  Core/WumpusCore/Trivia/Trivia.cs
  Core/WumpusCore/WumpusCore.csproj
  Core/WumpusCore/packages.config
  Core/WumpusTesting/TriviaTesting.cs
  Core/WumpusTesting/WumpusTesting.csproj
  Unity/.gitignore
Labels: enhancement
