Repository thewumper/Wumpus, pull requests merged in 2024-03, with the labels that each got.

#39 Fix Newtonsoft packages and add Unity packages
  .gitignore
  Core/.gitignore
  Core/WumpusCore/WumpusCore.csproj
  Unity/Packages/manifest.json
  Unity/Packages/packages-lock.json
Labels: bug

#44 Main Menu + Main Scene basic implementation
  Core/WumpusCore/Controller/Controller.cs
  Core/WumpusCore/Controller/ControllerState.cs
  Core/WumpusCore/Topology/Directions.cs
  Core/WumpusTesting/ControllerTest.cs
  Core/WumpusTesting/WumpusTesting.csproj
  Unity/Assets/Maps/map0.wmp
  Unity/Assets/Scenes/Main Menu.unity
  Unity/Assets/Scenes/Main.unity
  Unity/Assets/Scripts/MainMenuUI.cs
  Unity/Assets/Scripts/SceneController.cs
  Unity/Assets/Scripts/UI.cs
  Unity/Assets/black.mat
  Unity/ProjectSettings/SceneTemplateSettings.json
Labels: documentation, enhancement

#46 Entity gamelocations integration
  Core/WumpusCore/Entity/Entity.cs
  Core/WumpusCore/Entity/EntityType.cs
  Core/WumpusCore/GameLocations/GameLocations.cs
  Core/WumpusCore/WumpusCore.csproj
  Core/WumpusTesting/EntityTest.cs
Labels: enhancement, stub

#53 Add finished Entity
  Core/WumpusCore/Entity/Entity.cs
  Core/WumpusCore/GameLocations/GameLocations.cs
  Core/WumpusCore/Topology/IRoom.cs
  Core/WumpusCore/Topology/ITopology.cs
  Core/WumpusCore/Topology/Topology.cs
  Core/WumpusTesting/DummyEntity.cs
  Core/WumpusTesting/EntityTest.cs
  Core/WumpusTesting/TopologyTests.cs
  Core/WumpusTesting/TriviaTesting.cs
  Core/WumpusTesting/WumpusTesting.csproj
Labels: enhancement

#54 Change topology indexing from 1 to 0
  Core/WumpusCore/Controller/Controller.cs
  Core/WumpusCore/GameLocations/GameLocations.cs
  Core/WumpusCore/Topology/IRoom.cs
  Core/WumpusCore/Topology/ITopology.cs
  Core/WumpusCore/Topology/Topology.cs
  Core/WumpusTesting/DummyEntity.cs
  Core/WumpusTesting/EntityTest.cs
  Core/WumpusTesting/TopologyTests.cs
Labels: enhancement
